os:
  - windows
  - linux
  - osx
language: rust
rust:
  - stable
cache: cargo
matrix:
  fast_finish: true

script: cargo build --release --verbose
deploy:
  provider: releases
  api_key: $GITHUB_PAT
  file: $TRAVIS_FILENAME
  on:
    tags: true
  skip_cleanup: true
after_script:
  - >
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export TRAVIS_FILENAME=iron-distort.vst
      ./osx_bundle.sh iron-distort target/release/libirondistort.dylib;
    fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export TRAVIS_FILENAME=target/release/irondistort.dll; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export TRAVIS_FILENAME=target/release/libirondistort.so; fi
