[package]
name = "iron-distort"
version = "0.1.0"
authors = ["Nathan Graule <solarliner@gmail.com>"]
edition = "2018"

[dependencies]
atomic-db = {path="../atomic-db"}
vst = "0.2.0"

[lib]
name = "irondistort"
crate-type = ["cdylib"]
